### ISSUE TITLE
AttributeError: 'builtins.DT' object has no attribute 'add_attribute_map'

### ISSUE THREAD

**Issue by weiji14** [hugoledoux/startinpy#26]
When running the example at https://startinpy.readthedocs.io/0.11.0/attributes.html#retrieving-the-extra-attributes:

```python
dt = startinpy.DT()
dt.add_attribute_map(np.dtype([("classification", np.uint32)]))
dt.insert_one_pt([85000.0, 444003.2, 2.2], classification=6)
```

The following AttributeError is raised:

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'builtins.DT' object has no attribute 'add_attribute_map'
```

Has the `add_attribute_map` method been renamed to something else? Documentation should be updated to reflect the new method.

Xref review at https://github.com/openjournals/joss-reviews/issues/7123

**Comment by hugoledoux** [comment]
Indeed, the name of that function changed and I forgot that snippet. Thanks for catching that one.

Also, while going through the schema functions, I noticed that np.int32 and np.uint32 don't work because I use Rust serde Value and 64bits numbers are default, so I removed the 32bits (signed) integers for the schema, see 5c8ef298b89c78c39b7c54d8518a2a14cd9416aa

**Comment by weiji14** [comment]
Missed one more `add_attribute_map` -> `set_attributes_schema` rename here:

https://github.com/hugoledoux/startinpy/blob/5c8ef298b89c78c39b7c54d8518a2a14cd9416aa/src/lib.rs#L434
